version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
      PGDATA: /pg-data
    volumes:
      - db_data:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 2s
      retries: 5
    networks:
      - "django-network"
    expose:
      - "5432"
  django_web:
    build: .
    volumes:
      - ".:/container"
      - "static:/container/static"
      - "media:/container/media"
    env_file: [".env"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - "django-network"
    expose:
      - "8000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static:/var/data/static/
      - media:/var/data/media/
    ports:
      - "80:80"
    depends_on:
      - django_web
    networks:
      - "django-network"
networks:
  django-network:
    name: django-network

volumes:
  db_data:
  media:
  static:
